import { PrismaPg } from '@prisma/adapter-pg';
import { PrismaClient } from '../src/generated/prisma/client.js';
import * as bcrypt from 'bcrypt';

const connectionString = process.env.DATABASE_URL;

if (!connectionString) {
  throw new Error('DATABASE_URL is not configured');
}

const adapter = new PrismaPg({
  connectionString,
});

const prisma = new PrismaClient({
  adapter,
});

async function main() {
  const passwordHash = await bcrypt.hash(
    'Admin12345',
    12,
  );

  await prisma.user.upsert({
    where: {
      email: 'admin@example.com',
    },
    update: {},
    create: {
      email: 'admin@example.com',
      passwordHash,
      firstName: 'System',
      lastName: 'Administrator',
      role: 'ADMIN',
    },
  });

  await prisma.student.createMany({
      data: [
        {
          studentNumber: 'STU-0001',
          firstName: 'Ahmad',
          lastName: 'Yakubu',
          email: 'ahmadyakubuaya@mail.com',
          dateOfBirth: new Date('2002-01-15'),
          gender: 'MALE',
          department: 'Software Engineering',
          level: 400,
        },
        {
          studentNumber: 'STU-0002',
          firstName: 'Rahma',
          lastName: 'Ladan Galadima',
          email: 'rahmagaladimaladan@mail.com',
          dateOfBirth: new Date('2003-05-20'),
          gender: 'FEMALE',
          department: 'Information Technology',
          level: 300,
        },
        {
          studentNumber: 'STU-0003',
          firstName: 'Ibrahim',
          lastName: 'Musa',
          email: 'ibrahimmusa@mail.com',
          dateOfBirth: new Date('2001-08-12'),
          gender: 'MALE',
          department: 'Computer Science',
          level: 400,
        },
        {
          studentNumber: 'STU-0004',
          firstName: 'Aisha',
          lastName: 'Abdullahi',
          email: 'aishaabdullahi@mail.com',
          dateOfBirth: new Date('2003-02-28'),
          gender: 'FEMALE',
          department: 'Cybersecurity',
          level: 200,
        },
        {
          studentNumber: 'STU-0005',
          firstName: 'Abubakar',
          lastName: 'Sani',
          email: 'abubakarsani@mail.com',
          dateOfBirth: new Date('2002-11-05'),
          gender: 'MALE',
          department: 'Software Engineering',
          level: 300,
        },
        {
          studentNumber: 'STU-0006',
          firstName: 'Fatima',
          lastName: 'Bello',
          email: 'fatimabello@mail.com',
          dateOfBirth: new Date('2004-07-19'),
          gender: 'FEMALE',
          department: 'Information Technology',
          level: 200,
        },
        {
          studentNumber: 'STU-0007',
          firstName: 'Yusuf',
          lastName: 'Ibrahim',
          email: 'yusufibrahim@mail.com',
          dateOfBirth: new Date('2001-04-23'),
          gender: 'MALE',
          department: 'Computer Engineering',
          level: 400,
        },
        {
          studentNumber: 'STU-0008',
          firstName: 'Zainab',
          lastName: 'Ahmed',
          email: 'zainabahmed@mail.com',
          dateOfBirth: new Date('2003-09-14'),
          gender: 'FEMALE',
          department: 'Computer Science',
          level: 300,
        },
        {
          studentNumber: 'STU-0009',
          firstName: 'Omar',
          lastName: 'Usman',
          email: 'omarusman@mail.com',
          dateOfBirth: new Date('2002-06-30'),
          gender: 'MALE',
          department: 'Cybersecurity',
          level: 400,
        },
        {
          studentNumber: 'STU-0010',
          firstName: 'Maryam',
          lastName: 'Suleiman',
          email: 'maryamsuleiman@mail.com',
          dateOfBirth: new Date('2004-01-11'),
          gender: 'FEMALE',
          department: 'Software Engineering',
          level: 200,
        },
        {
          studentNumber: 'STU-0011',
          firstName: 'Abdullahi',
          lastName: 'Garba',
          email: 'abdullahigarba@mail.com',
          dateOfBirth: new Date('2001-12-03'),
          gender: 'MALE',
          department: 'Information Technology',
          level: 400,
        },
        {
          studentNumber: 'STU-0012',
          firstName: 'Hauwa',
          lastName: 'Mohammed',
          email: 'hauwamohammed@mail.com',
          dateOfBirth: new Date('2003-03-17'),
          gender: 'FEMALE',
          department: 'Computer Science',
          level: 300,
        },
        {
          studentNumber: 'STU-0013',
          firstName: 'Sadiq',
          lastName: 'Aliyu',
          email: 'sadiqaliyu@mail.com',
          dateOfBirth: new Date('2002-10-21'),
          gender: 'MALE',
          department: 'Software Engineering',
          level: 300,
        },
        {
          studentNumber: 'STU-0014',
          firstName: 'Khadija',
          lastName: 'Yusuf',
          email: 'khadijayusuf@mail.com',
          dateOfBirth: new Date('2004-05-08'),
          gender: 'FEMALE',
          department: 'Cybersecurity',
          level: 200,
        },
        {
          studentNumber: 'STU-0015',
          firstName: 'Mustapha',
          lastName: 'Lawal',
          email: 'mustaphalawal@mail.com',
          dateOfBirth: new Date('2001-07-26'),
          gender: 'MALE',
          department: 'Computer Engineering',
          level: 400,
        },
        {
          studentNumber: 'STU-0016',
          firstName: 'Asma',
          lastName: 'Hassan',
          email: 'asmahassan@mail.com',
          dateOfBirth: new Date('2003-11-13'),
          gender: 'FEMALE',
          department: 'Information Technology',
          level: 300,
        },
        {
          studentNumber: 'STU-0017',
          firstName: 'Hamza',
          lastName: 'Abubakar',
          email: 'hamzaabubakar@mail.com',
          dateOfBirth: new Date('2002-02-09'),
          gender: 'MALE',
          department: 'Computer Science',
          level: 200,
        },
        {
          studentNumber: 'STU-0018',
          firstName: 'Safiya',
          lastName: 'Mansur',
          email: 'safiyamansur@mail.com',
          dateOfBirth: new Date('2004-08-25'),
          gender: 'FEMALE',
          department: 'Software Engineering',
          level: 200,
        },
        {
          studentNumber: 'STU-0019',
          firstName: 'Nasir',
          lastName: 'Danjuma',
          email: 'nasirdanjuma@mail.com',
          dateOfBirth: new Date('2001-05-16'),
          gender: 'MALE',
          department: 'Cybersecurity',
          level: 400,
        },
        {
          studentNumber: 'STU-0020',
          firstName: 'Amina',
          lastName: 'Ibrahim',
          email: 'aminaibrahim@mail.com',
          dateOfBirth: new Date('2003-12-22'),
          gender: 'FEMALE',
          department: 'Computer Science',
          level: 300,
        },
        {
          studentNumber: 'STU-0021',
          firstName: 'Murtala',
          lastName: 'Shehu',
          email: 'murtalashehu@mail.com',
          dateOfBirth: new Date('2002-03-04'),
          gender: 'MALE',
          department: 'Information Technology',
          level: 400,
        },
        {
          studentNumber: 'STU-0022',
          firstName: 'Nafisa',
          lastName: 'Usman',
          email: 'nafisausman@mail.com',
          dateOfBirth: new Date('2004-06-18'),
          gender: 'FEMALE',
          department: 'Software Engineering',
          level: 200,
        },
        {
          studentNumber: 'STU-0023',
          firstName: 'Bashir',
          lastName: 'Abdullahi',
          email: 'bashirabdullahi@mail.com',
          dateOfBirth: new Date('2001-09-27'),
          gender: 'MALE',
          department: 'Computer Engineering',
          level: 300,
        },
        {
          studentNumber: 'STU-0024',
          firstName: 'Rukayya',
          lastName: 'Sani',
          email: 'rukayyasani@mail.com',
          dateOfBirth: new Date('2003-01-30'),
          gender: 'FEMALE',
          department: 'Cybersecurity',
          level: 300,
        },
        {
          studentNumber: 'STU-0025',
          firstName: 'Suleiman',
          lastName: 'Bello',
          email: 'suleimanbello@mail.com',
          dateOfBirth: new Date('2002-07-07'),
          gender: 'MALE',
          department: 'Computer Science',
          level: 400,
        },
        {
          studentNumber: 'STU-0026',
          firstName: 'Hajara',
          lastName: 'Yahaya',
          email: 'hajarayahaya@mail.com',
          dateOfBirth: new Date('2004-03-12'),
          gender: 'FEMALE',
          department: 'Information Technology',
          level: 200,
        },
        {
          studentNumber: 'STU-0027',
          firstName: 'Kabiru',
          lastName: 'Mamman',
          email: 'kabirumamman@mail.com',
          dateOfBirth: new Date('2001-11-18'),
          gender: 'MALE',
          department: 'Software Engineering',
          level: 400,
        },
        {
          studentNumber: 'STU-0028',
          firstName: 'Jamila',
          lastName: 'Abbas',
          email: 'jamilaabbas@mail.com',
          dateOfBirth: new Date('2003-06-04'),
          gender: 'FEMALE',
          department: 'Computer Science',
          level: 300,
        },
        {
          studentNumber: 'STU-0029',
          firstName: 'Ismail',
          lastName: 'Haruna',
          email: 'ismailharuna@mail.com',
          dateOfBirth: new Date('2002-09-09'),
          gender: 'MALE',
          department: 'Cybersecurity',
          level: 200,
        },
        {
          studentNumber: 'STU-0030',
          firstName: 'Maimuna',
          lastName: 'Abubakar',
          email: 'maimunaabubakar@mail.com',
          dateOfBirth: new Date('2004-10-15'),
          gender: 'FEMALE',
          department: 'Computer Engineering',
          level: 300,
        },
        {
          studentNumber: 'STU-0031',
          firstName: 'Salihu',
          lastName: 'Ahmad',
          email: 'salihuahmad@mail.com',
          dateOfBirth: new Date('2001-02-24'),
          gender: 'MALE',
          department: 'Information Technology',
          level: 400,
        },
        {
          studentNumber: 'STU-0032',
          firstName: 'Aisha',
          lastName: 'Musa',
          email: 'aishamusa@mail.com',
          dateOfBirth: new Date('2003-08-06'),
          gender: 'FEMALE',
          department: 'Software Engineering',
          level: 300,
        },
        {
          studentNumber: 'STU-0033',
          firstName: 'Faruk',
          lastName: 'Ibrahim',
          email: 'farukibrahim@mail.com',
          dateOfBirth: new Date('2002-04-19'),
          gender: 'MALE',
          department: 'Computer Science',
          level: 200,
        },
        {
          studentNumber: 'STU-0034',
          firstName: 'Bilkisu',
          lastName: 'Garba',
          email: 'bilkisugarba@mail.com',
          dateOfBirth: new Date('2004-12-01'),
          gender: 'FEMALE',
          department: 'Cybersecurity',
          level: 400,
        },
        {
          studentNumber: 'STU-0035',
          firstName: 'Abdulrahman',
          lastName: 'Yusuf',
          email: 'abdulrahmanyusuf@mail.com',
          dateOfBirth: new Date('2001-06-11'),
          gender: 'MALE',
          department: 'Software Engineering',
          level: 400,
        },
        {
          studentNumber: 'STU-0036',
          firstName: 'Zulaihat',
          lastName: 'Abdullahi',
          email: 'zulaihatabdullahi@mail.com',
          dateOfBirth: new Date('2003-10-29'),
          gender: 'FEMALE',
          department: 'Information Technology',
          level: 200,
        },
        {
          studentNumber: 'STU-0037',
          firstName: 'Nura',
          lastName: 'Mohammed',
          email: 'nuramohammed@mail.com',
          dateOfBirth: new Date('2002-12-16'),
          gender: 'MALE',
          department: 'Computer Engineering',
          level: 300,
        },
        {
          studentNumber: 'STU-0038',
          firstName: 'Hadiza',
          lastName: 'Suleiman',
          email: 'hadizasuleiman@mail.com',
          dateOfBirth: new Date('2004-04-07'),
          gender: 'FEMALE',
          department: 'Computer Science',
          level: 200,
        },
        {
          studentNumber: 'STU-0039',
          firstName: 'Mubarak',
          lastName: 'Ali',
          email: 'mubarakali@mail.com',
          dateOfBirth: new Date('2001-10-03'),
          gender: 'MALE',
          department: 'Cybersecurity',
          level: 400,
        },
        {
          studentNumber: 'STU-0040',
          firstName: 'Sadiya',
          lastName: 'Umar',
          email: 'sadiyaumar@mail.com',
          dateOfBirth: new Date('2003-07-21'),
          gender: 'FEMALE',
          department: 'Software Engineering',
          level: 300,
        },
        {
          studentNumber: 'STU-0041',
          firstName: 'Usman',
          lastName: 'Yahaya',
          email: 'usmanyahaya@mail.com',
          dateOfBirth: new Date('2002-05-14'),
          gender: 'MALE',
          department: 'Computer Science',
          level: 400,
        },
        {
          studentNumber: 'STU-0042',
          firstName: 'Maryam',
          lastName: 'Abdullahi',
          email: 'maryamabdullahi@mail.com',
          dateOfBirth: new Date('2004-09-02'),
          gender: 'FEMALE',
          department: 'Information Technology',
          level: 200,
        },
        {
          studentNumber: 'STU-0043',
          firstName: 'Anas',
          lastName: 'Musa',
          email: 'an​​asmusa@mail.com',
          dateOfBirth: new Date('2001-03-22'),
          gender: 'MALE',
          department: 'Software Engineering',
          level: 300,
        },
        {
          studentNumber: 'STU-0044',
          firstName: 'Fadila',
          lastName: 'Hassan',
          email: 'fadilahassan@mail.com',
          dateOfBirth: new Date('2003-11-07'),
          gender: 'FEMALE',
          department: 'Cybersecurity',
          level: 300,
        },
        {
          studentNumber: 'STU-0045',
          firstName: 'Ridwan',
          lastName: 'Sani',
          email: 'ridwansani@mail.com',
          dateOfBirth: new Date('2002-08-28'),
          gender: 'MALE',
          department: 'Computer Engineering',
          level: 400,
        },
        {
          studentNumber: 'STU-0046',
          firstName: 'Sumayya',
          lastName: 'Bello',
          email: 'sumayyabello@mail.com',
          dateOfBirth: new Date('2004-02-13'),
          gender: 'FEMALE',
          department: 'Computer Science',
          level: 200,
        },
        {
          studentNumber: 'STU-0047',
          firstName: 'Abdulaziz',
          lastName: 'Garba',
          email: 'abdulazizgarba@mail.com',
          dateOfBirth: new Date('2001-12-27'),
          gender: 'MALE',
          department: 'Information Technology',
          level: 400,
        },
        {
          studentNumber: 'STU-0048',
          firstName: 'Nana',
          lastName: 'Ibrahim',
          email: 'nanaibrahim@mail.com',
          dateOfBirth: new Date('2003-04-16'),
          gender: 'FEMALE',
          department: 'Software Engineering',
          level: 300,
        },
        {
          studentNumber: 'STU-0049',
          firstName: 'Tahir',
          lastName: 'Lawal',
          email: 'tahirlawal@mail.com',
          dateOfBirth: new Date('2002-10-10'),
          gender: 'MALE',
          department: 'Cybersecurity',
          level: 200,
        },
        {
          studentNumber: 'STU-0050',
          firstName: 'Faiza',
          lastName: 'Mohammed',
          email: 'faizamohammed@mail.com',
          dateOfBirth: new Date('2004-06-26'),
          gender: 'FEMALE',
          department: 'Computer Science',
          level: 400,
        },
      ],
    skipDuplicates: true,
  });

  console.log('Database seeded successfully');
}

main()
  .catch((error) => {
    console.error(error);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
